### ISSUE TITLE
In the README.md put some Purpose and/or Scope section.

### ISSUE THREAD

**Issue by lofstrandbjorn** [MSG134/IVCT_Compositions#5]
The Read me should provide enough information for the reader to understand the primary purpose of IVCT. This is likely the first info the first-time reader get so a clear and concise intro is required. Even if the link to full documentation is there it would be good to highlight the most important intro directly in the README. Perhaps some very easy image.

**Comment by bergtwvd** [comment]
We can integrate parts of the SIW paper. TBD.

**Comment by rhzg** [comment]
I have updated the README with hopefully some more helpful introductions

**Comment by bergtwvd** [comment]
Fine by me, lets close.
